version: "3.8"

services:
  web:
    image: ghcr.io/dzo4e2250/nikermanas-ancient-tome:latest
    container_name: nikermanas-web
    ports:
      - "5678:80"
      - "5677:5677"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup
