// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzgrrqabijoikoyjlxmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6Z3JycWFiaWpvaWtveWpseG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDgwNjYsImV4cCI6MjA2OTc4NDA2Nn0.looientnSmtUf-PbEO4gZ97Zpnh_uC7TXTrhQVJ5jvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});